name = "ag-decoder-worker"
main = "main.py"
compatibility_date = "2024-05-02"
compatibility_flags = ["python_workers"]

[python_modules]
excludes = [
  "**/*.db",
  "**/*.sql",
  "**/*.zip",
  "**/*.pdf",
  "d1_migration.sql",
  "ag_decoder.db",
  "Book1.pdf",
  "Book2.pdf",
  "d1_migration.zip",
  "configure_dns.py",
  "setup_cloudflare.py",
  "generate_d1_db.py",
  "setup_local_db.py",
  "import_local_json_ranges.py"
]

[[d1_databases]]
binding = "DB"
database_name = "ag-decoder-db"
database_id = "5f77db29-a6d3-423d-a3f4-126fac38f1b2"
